services:
   adguardhome:
        image: adguard/adguardhome
        container_name: adhome
        restart: unless-stopped
        ports:
                # udp dns
                - 53:53/tcp
                - 53:53/udp
                # dhcp
                #- 67:67/udp
                #- 68:68/udp
                
                # doh
                - 80:80/tcp
                - 443:443/tcp
                - 443:443/udp
               
                # dot
                - 853:853/tcp

                # doq
                - 784:784/udp
                - 853:853/udp
                - 8853:8853/udp

                # admin panel
                - 3000:3000/tcp
        volumes:
                - "./work:/opt/adguardhome/work"
                - "./conf:/opt/adguardhome/conf"
